### ISSUE TITLE
[Inspection] Class is not instantiable for type that is supported by Dalesbred

### ISSUE THREAD

**Issue by egaga** [EvidentSolutions/dalesbred-idea-plugin#2]
The idea plugin complains that LocalDate class is not instantiable, even though Dalesbred has a type conversion for LocalDate by default.

    return db.findAll(LocalDate.class, "select d from foo");

There might be similar issues for other types that are supported by default.

Plugin version is 0.2.9

**Comment by hakuzumon** [comment]
`InputStream` gives a warning too.
